@startuml

<style>
title {
  HorizontalAlignment right
  FontSize 24
  FontColor blue
}

header {
  HorizontalAlignment center
  FontSize 18
  ' FontColor purple
}

footer {
  HorizontalAlignment left
  FontSize 28
  FontColor red
}

legend {
  FontSize 15
  BackGroundColor yellow
  Margin 10
  Padding 5
}

caption {
  FontSize 32
}

arrow {
  FontSize 18
  Padding 50
  Margin 50
}

</style>

header Draft

title IDEA4RC DataModel

' hide the spot
hide circle

' avoid problems with angled crows feet
skinparam linetype ortho
scale 0.5



object "Patient" as p {
- <color:blue>Sex</color>
- <color:blue>Race</color>
- <color:blue>BirthYear</color>
- <color:blue>CountryOfResidence</color>
- <color:blue>Smoking</color>
# <color:blue>CigarettesOrCigarsSmokedPerDay</color>
- <color:blue>Alcohol</color>
# <color:red>BMI</color>
# <color:blue>CharlsonComorbidityIndex</color>
- <color:red>Comorbidity</color>
+ <color:red>MyocardialInfarction</color>
+ <color:red>CongestiveHeartFailure</color>
+ <color:red>PeripheralVascularDisease</color>
+ <color:red>CerebrovascularAccidentExceptHemiplegia</color>
+ <color:red>Dementia</color>
+ <color:red>ChronicPulmonaryDisease</color>
+ <color:red>ConnectiveTissueDisease</color>
+ <color:red>Ulcer</color>
+ <color:red>MildLiverDisease</color>
+ <color:red>ModerateToSevereLiverDisease</color>
+ <color:red>DiabetesWithoutComplications</color>
+ <color:red>DiabetesWithEndOrganDamage</color>
+ <color:red>Hemiplegia</color>
+ <color:red>ModerateToSevereRenalDisease</color>
+ <color:red>SolidTumorNonMetastatic</color>
+ <color:red>MetastaticSolidTumor</color>
+ <color:red>Leukemia</color>
+ <color:red>Lymphoma</color>
+ <color:red>MultipleMyeloma</color>
+ <color:red>Aids</color>
# <color:red>ecogPS</color>
# <color:red>ecogPSlabel</color>
# <color:red>KarnofsyIndexAtDiagnosis</color>
# <color:red>KarnofsyIndexLabel</color>
- <color:green>NoGeneticSyndrome</color>
- <color:green>OlliersDisease</color>
- <color:green>MaffuciSyndrome</color>
- <color:green>LiFraumeniSyndrome</color>
- <color:green>McCuneAlbrightSyndrome</color>
- <color:green>MultipleOsteochondromas</color>
- <color:green>NeurofibromatosisType1</color>
- <color:green>RothmundThomsonSyndrome</color>
- <color:green>WernerSyndrome</color>
- <color:green>Retinoblastoma</color>
- <color:green>PagetDisease</color>
- <color:green>OtherGeneticSyndrome</color>
# <color:green>PreviousMalignantCancerSite</color>
# <color:green>PreviousCancerTreatment</color>

    }
object "CancerEpisode" as ce {
    - <color:blue>Patient</color>
- <color:blue>cancerStartDate</color>

    }
object "PatientFollowUp" as pfu {
- <color:blue>Patient</color>
- <color:blue>StatusAtLastFollowUp</color>
- <color:blue>PatientFollowUpDate</color>
- <color:red>NewCancerDiagnosis</color>
- <color:red>DateOfNewCancerDiagnosis</color>
- <color:red>NewCancerTopography</color>
- <color:green>LastContact</color>

    }
object "HospitalPatientRecords" as hpr {
    - <color:red>patient</color>
- <color:red>hospital</color>
- <color:red>dateOfFirstContactWithTheHospital</color>

    }


object "HospitalData" as hd {
    - <color:red>hospitalName</color>

    }
object "Diagnosis" as d {
    - <color:blue>cancerEpisode</color>
    - <color:blue>dateOfDiagnosis</color>
    - <color:green>typeOfBiopsy</color>
    - <color:blue>biopsyDoneBy</color>
    - <color:blue>ageAtDiagnosis</color>
    - <color:green>radiotherapyInducedSarcoma</color>
    + <color:blue>biopsyGrading</color>
    - <color:blue>histologyGroup</color>
    - <color:blue>site</color>
    - <color:blue>histologySubgroup</color>
    - <color:blue>subsite</color>
    - <color:blue>diagnosisCode</color>
    - <color:green>tumorSize</color>
    - <color:green>superficialDepth</color>
    - <color:green>deepDepth</color>
    - <color:green>biopsyMitoticCount</color>
    - <color:green>mitoticIndex</color>
    - <color:red>plasmaticEbvDnaAtBaseline</color>
    - <color:red>hpvStatus</color>
    + <color:red>crpCReactiveProteinTested</color>


}


object "EpisodeEvent" as ee {
    - <color:blue>cancerEpisode</color>
- <color:blue>EventType</color>
+ <color:blue>DefinedAt</color>
- <color:blue>DateOfEpisode</color>
   }
object "Surgery" as s {
    - <color:blue>diagnosisReference</color>
    - <color:blue>episodeEventReference</color>
    - <color:green>surgeryType</color>
    - <color:red>surgeryHospital</color>
    - <color:blue>dateOfSurgery</color>
    + <color:blue>surgeryIntention</color>
    - <color:red>typeOfSurgicalApproachOnTumour</color>
    - <color:blue>marginsAfterSurgery</color>
    - <color:green>tumorRupture</color>
    - <color:red>extraNodalExtension</color>
    - <color:green>surgicalSpecimenMitoticCount</color>
    - <color:green>surgicalSpecimenGradingOnlyInUntreatedTumours</color>
    - <color:red>reconstruction</color>
    - <color:red>neckSurgery</color>
    - <color:red>dateOfNeckSurgery</color>
    - <color:red>lateralityOfTheDissection</color>
    - <color:red>surgeryOnM</color>
    - <color:red>dateOfSurgeryOnM</color>
    + <color:red>siteOfSurgeryOnMetastasisSoftTissue</color>
    + <color:red>siteOfSurgeryOnMetastasisDistantLymphNodes</color>
    + <color:red>siteOfSurgeryOnMetastasisLung</color>
    + <color:red>siteOfSurgeryOnMetastasisBone</color>
    + <color:red>siteOfSurgeryOnMetastasisLiver</color>
    + <color:red>siteOfSurgeryOnMetastasisPeritoneum</color>
    + <color:red>siteOfSurgeryOnMetastasisBrain</color>
    + <color:red>siteOfSurgeryOnMetastasisOtherViscera</color>
    + <color:red>siteOfSurgeryOnMetastasisUnknown</color>
    - <color:red>surgicalComplications</color>
}

object "Radiotherapy" as r {
    - <color:blue>diagnosisReference</color>
    - <color:blue>episodeEventRefence</color>
    - <color:blue>radiotherapyHospital</color>
    - <color:blue>intent</color>
    - <color:blue>setting</color>
    - <color:red>beamQuality</color>
    + <color:red>otherSpecify</color>
    - <color:red>treatmentTechnique</color>
    - <color:blue>totalDoseGy</color>
    # <color:red>totalHighDose</color>
    - <color:blue>numberOfFractions</color>
    + <color:red>adaptiveRT</color>
    + <color:red>igrt</color>
    + <color:red>reirradiation</color>
    + <color:red>fieldOfReirradiation</color>
    - <color:blue>startDate</color>
    - <color:blue>endDate</color>
    - <color:red>treatmentSitePrimaryOnly</color>
    - <color:red>treatmentSiteNeckOnly</color>
    - <color:red>treatmentSitePrimaryAndIpsilateralNeck</color>
    - <color:red>treatmentSitePrimaryAndBilateralNeck</color>
    - <color:red>treatmentSiteDistantMetastasis</color>
    + <color:red>OtherTreatmentSite</color>
    # <color:blue>metastaticTreatmentSiteLung</color>
    # <color:blue>metastaticTreatmentSiteMediastinum</color>
    # <color:blue>metastaticTreatmentSiteBone</color>
    # <color:blue>metastaticTreatmentSiteSoftTissue</color>
    # <color:blue>metastaticTreatmentSiteLiver</color>
    - <color:blue>rtTreatmentCompletedAsPlanned</color>
    - <color:red>regionalDeepHyperthermia</color>
    # <color:red>treatmentResponse</color>
}
object "PathologicalStage" as ps {
    - <color:blue>diagnosisReference</color>
    - <color:red>StagingProceduresDoneBy</color>
    
}

object "ClinicalStage" as cs {
    - <color:blue>diagnosisReference</color>
    - <color:red>stagingProceedingsDoneBy</color>
    - <color:blue>imagingForPrimarySite</color>
    # <color:blue>ctForPrimarySite</color>
    # <color:blue>mriForPrimarySite</color>
    # <color:blue>usForPrimarySite</color>
    # <color:blue>otherImagingForPrimarySite</color>
    - <color:blue>imagingForNeck</color>
    # <color:blue>ctForNeck</color>
    # <color:blue>mriForNeck</color>
    # <color:blue>usForNeck</color>
    # <color:blue>otherImagingForNeck</color>
    - <color:blue>imagingForMetastasis</color>
    # <color:blue>ctForMetastasis</color>
    # <color:blue>mriForMetastasis</color>
    # <color:blue>usForMetastasis</color>
    # <color:blue>otherImagingForMetastasis</color>
    - <color:red>cT</color>
    - <color:red>cN</color>
    - <color:red>cM</color>
    - <color:red>extranodalExtension</color>
    - <color:red>clinicalStaging</color>
    - <color:green>localised</color>
    # <color:green>numberOfTumorNodules</color>
    - <color:green>locoRegional</color>
    - <color:blue>IsTransitMetastasisWithClinicalConfirmation</color>
    - <color:blue>isMultifocalTumor</color>
    - <color:blue>regionalNodalMetastases</color>
    # <color:blue>softTissue</color>
    # <color:blue>distantLymphNode</color>
    # <color:blue>isMultifocalTumor</color>
    # <color:blue>metastasisBone</color>
    # <color:blue>liver</color>
    # <color:blue>pleura</color>
    # <color:blue>peritoneum</color>
    # <color:blue>brain</color>
    # <color:blue>otherViscera</color>
    # <color:blue>unknown</color>
}
object "SystemicTreatment" as st {
    - <color:blue>diagnosisReference</color>
    - <color:blue>episodeEvent</color>
    - <color:blue>systemicTreatmentHospital</color>
    - <color:blue>typeOfSystemicTreatment</color>
    + <color:red>intent</color>
    + <color:red>setting</color>
    + <color:green>chemotherapyInfo</color>
    - <color:blue>startDateSystemicTreatment</color>
    - <color:blue>endDateSystemicTreatment</color>
    + <color:blue>numberOfCyclesAdministrations</color>
    + <color:blue>regimen</color>
    - <color:red>startDateRegimenChanged</color>
    - <color:red>endDateRegimenChanged</color>
    - <color:blue>reasonForEndOfTreatment</color>
    - <color:blue>treatmentResponse</color>
}
object "IsolatedLimbPerfusion" as ilp {
    - <color:green>diagnosisReference</color>
    - <color:green>episodeEvent</color>
    - <color:green>isolatedLimbPerfusionHospital</color>
    - <color:green>startDate</color>
    - <color:green>endDate</color>
    - <color:green>treatmentResponse</color>
}
object "OverallTreatmentResponse" as otr {
    - <color:blue>diagnosisReference</color>
    - <color:blue>episodeEventRefence</color>
    - <color:blue>overallTreatmentResponse</color>
    - <color:blue>overallTreatmentResponseDefined/Done</color>
}
object "GeneticTestExpression" as gte {
    - <color:red>diagnosisReference</color>
    - <color:red>episodeEventReference</color>
    # <color:red>geneExpressionAnalysisPerformed</color>
    + <color:red>dateOfGeneExpression</color>
    # <color:red>geneMutationAnalysisPerformed</color>
    + <color:red>dateOfGeneMutation</color>
    # <color:red>testForChromosomeTranslocationsPerformed</color>
    + <color:red>dateOfTranslocation</color>
    # <color:red>nextGenerationSequencingPerformed</color>
    + <color:red>dateOfNGS</color>
    # <color:red>polymeraseChainReactionTestPerformed</color>
    + <color:red>dateOfPCR</color>
    # <color:red>immunohistochemistryPerformed</color>
    + <color:red>dateOfImmunohistochemistry</color>
    # <color:red>circulatingTumourDnaPerformed</color>
    + <color:red>dateOfCtDNA</color>
}
object "AdverseEvent" as ae {
    - <color:red>treatmentReference</color>
    - <color:red>adverseEventType</color>
    - <color:red>adverseEventStartingDate</color>
    - <color:red>adverseEventDuration</color>
}
object "DrugsForTreatments" as dft {
    - <color:blue>systemicTreatment</color>
    - <color:blue>otherLocalTreatment</color>
    - <color:blue>isolatedLimbPerfusion</color>
    - <color:blue>isolatedLimbPerfusion</color>
}
object "RegionalDeepHyperthemia" as rdh {
    - <color:green>diagnosisReference</color>
    - <color:green>episodeEvent</color>
    - <color:green>regionalDeepHyperthemiaDoneAtHospital</color>
    - <color:green>startDate</color>
    - <color:green>endDate</color>
    - <color:green>treatmentResponse</color>
}

p "1" ||--|{ "1..N" hpr
p "1" ||--o{ "0..N" pfu
p "1" ||--o{ "1..N" ce
ce "1" ||--|{ "1..N" d
ce "1" ||--|{ "0..N" ee
hd "1" ||--|{ "1..N" hpr
ee "1" ||--o{ "0..N" r  
ee "1" ||--o{ "0..N" s 
ee "1" ||--o{ "0..1" d
ee "1" ||--o{ "0..N" st
ee "1" ||--o{ "0..N" rdh
ee "1" ||--o{ "0..N" ilp
ee "1" ||--o{ "0..N" gte
ee "1" ||--o{ "0..1" otr
d "1" ||--o{ "0..N" r
d "1" ||--o{ "0..N" s
d "1" ||--o{ "0..1" ps
d "1" ||--o{ "0..1" cs
d "1" ||--o{ "0..N" st
d "1" ||--o{ "0..N" rdh
d "1" ||--o{ "0..N" ilp
d "1" ||--o{ "0..N" gte
d "1" ||--o{ "0..1" otr
st "1"||--o{ "0..N" dft
ilp "1"||--o{ "0..N" dft
ilp "1"||--o{ "0..N" rdh



note as N1
The relations to AdverseEvent are a XOR
end note

s "1" ||--o{ "0..N" ae
'note on link: XOR
st "0..N" ||--o{ "1" ae
'note on link: XOR
r "1" ||--o{ "0..N" ae
'note on link: XOR

s .. N1
st .. N1
r .. N1
legend
Text color:
Blue -> H&N, Sarc. 
Red -> H&N
Green -> Sarc.
---------
Shapes:
red -> Mandatory
yellow -> Recommended
green -> Optional
---------
Each variable (and entity if needed) is related to the datamodels,
HN means Head and Neck
S means Sarcoma
end legend
@enduml